In [2]:
import numpy as np

# OR gatetruth table
X = np.array([[0, 0],
             [0, 1],
             [1, 0],
             [1, 1]])
Y = np.array ([[0],
              [1],
              [1],
              [1]])

# Four inputs, each paif of bits. Four expected outputs.
# That's the entire dataset -  no noise, no ambiguity, so if neuron doesn't learn it, the bug is in our math!! 
# not in the data.

In [4]:
# Initialize weights and bias. 
np.random.seed(42)  # so we get the same "random" numbers every run — reproducibility matters when comparing notebooks

weights = np.random.randn(2, 1)  # shape (2,1) — one weight per input feature
bias = np.random.randn(1)        # a single scalar bias

print("weights:\n", weights)
print("bias:", bias)

weights:
 [[ 0.49671415]
 [-0.1382643 ]]
bias: [0.64768854]


In [5]:
# The forward pass (weighted sum + Activation function)
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def forward(X, weights, bias):
    z = np.dot(X, weights) + bias   # weighted sum: (4,2) @ (2,1) -> (4,1), then add bias
    a = sigmoid(z)                   # squash into (0,1) range
    return a

predictions = forward(X, weights, bias)
print(predictions)

[[0.65648939]
 [0.62467149]
 [0.75848706]
 [0.73226375]]


In [12]:
# The loss function (Mean Squared Error)
def mse_loss(Y_true, y_pred):
    return np.mean((Y_true - y_pred) ** 2)

loss = mse_loss(Y, predictions)
print("Loss:", loss)

Loss: 0.17546525262263657


In [13]:
# Backpropagation (Computing gradients manually)
def backward(X, Y, a):
    n = Y.shape[0]
    
    dL_da = (2 / n) * (a - Y)          # Step 1: loss w.r.t. prediction
    da_dz = a * (1 - a)                 # Step 2: sigmoid derivative
    dL_dz = dL_da * da_dz               # Step 3: chain rule combines them
    
    dL_dw = np.dot(X.T, dL_dz)          # Step 4a: gradient w.r.t. weights
    dL_db = np.sum(dL_dz)                # Step 4b: gradient w.r.t. bias
    
    return dL_dw, dL_db

dW, dB = backward(X, Y, predictions)
print("Gradient for weights:\n", dW)
print("Gradient for bias:", dB)

Gradient for weights:
 [[-0.04836603]
 [-0.07024452]]
Gradient for bias: -0.01834241677719908


Gradient descent update + the training loop

Why: We now have gradients (dW, dB) telling us which direction makes the loss worse. Gradient descent just means: move the opposite direction, by a small amount. That "small amount" is controlled by a number called the learning rate — too big and the neuron overshoots and never settles; too small and it learns painfully slowly.

The update rule is simple:

weights = weights - learning_rate * dW
bias = bias - learning_rate * dB

In [14]:
learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    # forward pass
    predictions = forward(X, weights, bias)
    
    # compute loss
    loss = mse_loss(Y, predictions)
    
    # backward pass
    dW, dB = backward(X, Y, predictions)
    
    # update weights and bias
    weights = weights - learning_rate * dW
    bias = bias - learning_rate * dB
    
    # print progress occasionally
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

Epoch 0, Loss: 0.1755
Epoch 1000, Loss: 0.0395
Epoch 2000, Loss: 0.0187
Epoch 3000, Loss: 0.0117
Epoch 4000, Loss: 0.0084
Epoch 5000, Loss: 0.0065
Epoch 6000, Loss: 0.0052
Epoch 7000, Loss: 0.0044
Epoch 8000, Loss: 0.0038
Epoch 9000, Loss: 0.0033


In [15]:
# Test the trained neuron
final_predictions = forward(X, weights, bias)

print("Final predictions:")
print(final_predictions)

print("\nRounded (0 or 1):")
print(np.round(final_predictions))

print("\nActual Y:")
print(Y)

Final predictions:
[[0.08126325]
 [0.94957602]
 [0.94959265]
 [0.99975074]]

Rounded (0 or 1):
[[0.]
 [1.]
 [1.]
 [1.]]

Actual Y:
[[0]
 [1]
 [1]
 [1]]


## Milestone: First Neuron, Trained From Scratch ✅

**Status:** Complete

We built and trained a single neuron using nothing but NumPy — no PyTorch, no autograd, no shortcuts. Every piece was hand-derived and hand-coded:

- Forward pass (weighted sum + sigmoid activation)
- Mean Squared Error loss
- Backpropagation, derived manually via the chain rule
- Gradient descent update loop
- Trained and verified on the OR gate — predictions matched ground truth after training

This confirms the neuron actually *learned* the underlying logic, not just memorized a low loss number.

### What's Next
- [ ] Compare notebooks — NJR vs SA, same math, independent implementations
- [ ] Attempt XOR — a known limitation for a single neuron, and the natural motivation for going multi-layer
- [ ] Eventually extend Genesis into a small multi-layer network, once XOR proves the point

**Genesis v1 is done.** First real proof that either of us can build a learning system from raw math — no framework doing the thinking for us.